### ISSUE TITLE
The Editor

### ISSUE THREAD

**Issue by JaydenDev** [screech-org/editor#1]
Alright, so an editor. Here's some options, you can add more any time by editing the comment.

- Tailwind/HTML/JS
- HTML/CSS/JS
- HTML/CSS/TS
- Svelte
- SvelteKit
- Vue
- React
- React + NextJS
- Pure vanilla HTML/CSS/JS
- JS free HTML/CSS

**Comment by UniqueName12345** [comment]
>     * JS free HTML/CSS

Wonder how that will turn out.

**Comment by Weredime** [comment]
TypeScript scratch-gui is what's going to happen

**Comment by Weredime** [comment]
> > ```
> > * JS free HTML/CSS
> > ```
> 
> Wonder how that will turn out.

That's literally impossible lol

**Comment by UniqueName12345** [comment]
> > > ```
> > > * JS free HTML/CSS
> > > ```
> > 
> > 
> > Wonder how that will turn out.
> 
> That's literally impossible lol

Then why put it there in the first place?

**Comment by JaydenDev** [comment]
> > > > ```
> > > > * JS free HTML/CSS
> > > > ```
> > > 
> > > 
> > > Wonder how that will turn out.
> > 
> > 
> > That's literally impossible lol
> 
> Then why put it there in the first place?

Options are options, the more options the more options.

**Comment by UniqueName12345** [comment]
> > > > > ```
> > > > > * JS free HTML/CSS
> > > > > ```
> > > > 
> > > > 
> > > > Wonder how that will turn out.
> > > 
> > > 
> > > That's literally impossible lol
> > 
> > 
> > Then why put it there in the first place?
> 
> Options are options, the more options the more options.

Can't argue with you _there._

**Comment by kccuber-scratch** [comment]
Closed. We forked the Scratch editor now.
